# Association Rule Mining R Script
# Adapted from David Schuff, MIS Department, Fox School of Business, Temple University
# Adapted from: http://prdeepakbabu.wordpress.com/2010/11/13/market-basket-analysisassociation-rule-mining-using-r-package-arules/

# First, clear all previous stuff out of the workspace...
rm(list = ls())

# VARIABLES - THIS SECTION HAS THE STUFF YOU SHOULD CHANGE.
# ** With a few exceptions, everything you'd modify is in this section. **
# ** Everything else (unless specified), LEAVE ALONE!!					**
# INPUT_FILENAME    The name of the file that contains the data (CSV format)
# OUTPUT_FILENAME	  This file is generated by R and will contain a list of association rules.
# SUPPORT_THRESH 	  The minimum threshold for support; below this the rule won't appear in the output.
# CONF_THRESH		    The minimum threshold for confidence; below this the rule won't appear in the output.
# CONF_THRESH_PLOT  Below this, the rule won't appear in the interactive plot. Usually this is more 
#      restrictive	(higher) than CONF_THRESH - a lot of rules in our plot is confusing!
INPUT_FILENAME 		<- "Bank.csv"
OUTPUT_FILENAME 	<- "ARulesOutput.csv"
SUPPORT_THRESH 		<- 0.01
CONF_THRESH      	<- 0.01

set.seed(1234)         # Fix the random seed - keeps the bubble charts the same with each run.

# Check for, and install if needed, the arules package:
# arules     - computes the association rules

if (!require("arules")) { install.packages("arules")
  require("arules") }

# Read the comma-delimited data file and put them into a variable called "txn." Make sure:
#     1) The first column has the transaction ID (not unique)
#     2) The second column has the "event" (i.e., product purchased; not unique either)
#     3) DON'T MESS WITH ANYTHING IN THE LINE BELOW. SPECIFY THE FILENAME ABOVE!
#
# By the way...rm.duplicates=TRUE removes double-counted items in a single basket, and 
# 		format="single" says each component of a transaction is on a separate line
#     sep="," tells R to look for a comma to separate data columns
#     cols=c(1,2) tells R to only look at the first two columns of the file
#      (there are only two columns in our file anyway, but just in case we throw it in there...)

txn = read.transactions(file=INPUT_FILENAME, rm.duplicates=TRUE, format="single",sep=",",cols=c(1,2))

# Run the apriori algorithm - this is what computes the association rules.
# DON'T MESS WITH THIS EITHER! CHANGE THE PARAMETERS IN THE VARIABLE LIST ABOVE!!
# txn -    the variable representing the transaction data read from the data file
# sup -    the minimum threshold for support; below this the rule won't appear in the output
# conf -   the minimum threshold for confidence; below this the rule won't appear in the output
# target - says we want to make some rules!

basket_rules <- apriori(txn,parameter = list(sup=SUPPORT_THRESH, conf=CONF_THRESH, target="rules"))

# This (1) outputs the list of rules to the screen and (2) writes them to a file.
# It's easier to see them if you just open the output file in Excel. You can also use Excel
#    to sort the rules by confidence, support, and lift.
#    (sep="," tells R to put a comma in between output in columns to make it look nicer when viewed)
inspect(basket_rules)
write.csv(as(basket_rules,"data.frame"), file = OUTPUT_FILENAME)
